import re
from typing import Dict, List, Tuple


class SanskritGrammar:
    """
    The Structural Engine (Left Brain Foundation).

    Implements Paninian rules (Sandhi, Vibhakti) to structure the
    stream of consciousness generated by the Right Brain.
    """

    def __init__(self):
        # Basic Vowel Sandhi Rules (Dirgha Sandhi, Guna Sandhi)
        # a/ā + a/ā -> ā
        # a/ā + i/ī -> e
        # a/ā + u/ū -> o
        self.sandhi_rules = {
            r'(a|ā)\s+(a|ā)': 'ā',
            r'(a|ā)\s+(i|ī)': 'e',
            r'(a|ā)\s+(u|ū)': 'o',
            r'(i|ī)\s+(a|ā)': 'ya', # Yan Sandhi
            r'(u|ū)\s+(a|ā)': 'va', # Yan Sandhi
            # Visarga Sandhi (simplified)
            r'ah\s+([gdjbvmnylrh])': r'o \1', # ah + voiced -> o
            r'ah\s+([a])': r'o \1', # ah + a -> o '
        }

        # Basic Vibhakti (Case) Endings for 'a' ending nouns (masculine)
        # Concept -> Nominative (Agent), Accusative (Object), etc.
        self.vibhakti_map = {
            'agent': 'ah',    # Rama -> Ramah (Nominative Sing.)
            'object': 'am',   # Rama -> Ramam (Accusative Sing.)
            'instrument': 'ena', # Rama -> Ramena (Instrumental Sing.)
            'source': 'at',   # Rama -> Ramat (Ablative Sing.)
            'relation': 'asya', # Rama -> Ramasya (Genitive Sing.)
            'location': 'e',  # Rama -> Rame (Locative Sing.)
        }
        self.action_set = {
            'go','move','run','walk','eat','drink','see','know','think','slip','fall','help','fight','love','hate','make','do','rain'
        }
        self.instrument_set = {
            'with','using','tool','knife','gun','sword','pen'
        }
        self.location_set = {
            'river','bank','home','house','city','village','forest','mountain','water','sea'
        }
        self.relation_set = {
            'of','from','to','for','by','on','in','at'
        }

    def apply_sandhi(self, text: str) -> str:
        """
        Applies phonetic fusion rules to smooth the stream of consciousness.
        """
        refined_text = text
        for pattern, replacement in self.sandhi_rules.items():
            refined_text = re.sub(pattern, replacement, refined_text, flags=re.IGNORECASE)
        return refined_text

    def apply_vibhakti(self, word: str, role: str) -> str:
        """
        Applies case endings based on thematic role (Karaka).
        """
        if role in self.vibhakti_map:
            # Very simplified: Assume 'a' stem for now
            if word.endswith('a'):
                return word[:-1] + self.vibhakti_map[role]
            else:
                return word + self.vibhakti_map[role] # Fallback
        return word

    def structure_thought(self, trajectory: List[str], roles: List[str] = None) -> str:
        """
        Takes a raw sequence of concepts (Right Brain output) and
        structures it into a coherent sentence using Grammar.
        """
        # 1. Identify Roles (Heuristic for now)
        # First concept = Agent (Kartru)
        # Last concept = Action (Kriya)
        # Middle = Object/Instrument

        if not trajectory:
            return ""

        structured_words = []

        if roles and len(roles) == len(trajectory):
            for w, r in zip(trajectory, roles):
                if r == 'verb':
                    structured_words.append(w + "ti")
                else:
                    structured_words.append(self.apply_vibhakti(w, r))
        else:
            subject = trajectory[0]
            structured_words.append(self.apply_vibhakti(subject, 'agent'))
            for word in trajectory[1:-1]:
                structured_words.append(self.apply_vibhakti(word, 'object'))
            if len(trajectory) > 1:
                action = trajectory[-1]
                structured_words.append(action + "ti")

        # Join
        raw_sentence = " ".join(structured_words)

        # Apply Sandhi
        final_sentence = self.apply_sandhi(raw_sentence)

        return final_sentence

    def compute_roles(self, concepts: List[str]) -> List[str]:
        roles = []
        n = len(concepts)
        for i, w in enumerate(concepts):
            wl = w.lower()
            if wl in self.action_set:
                roles.append('verb')
                continue
            if wl in self.instrument_set:
                roles.append('instrument')
                continue
            if wl in self.location_set:
                roles.append('location')
                continue
            if wl in self.relation_set:
                roles.append('relation')
                continue
            if i == 0:
                roles.append('agent')
            elif i == n - 1:
                roles.append('verb')
            else:
                roles.append('object')
        return roles
